### ISSUE TITLE
Sugerencia para la cátedra

### ISSUE THREAD

**Issue by Clirussa** [INGCOM-UNRN-P1/cursada-2023#33]
Hola, les quiero pedir profes que consideren hasta el domingo como fecha límite para la entrega de las prácticas por favor. Ésto lo pido por cuestiones laborales.

**Comment by martinvilu** [comment]
Siendo que el TP0 es _particularmente_ breve, (casi un diagnóstico de uso de la computadora). Tiene sentido que la fecha de entrega sea casi de un día para otro. En particular, el objetivo del TP0 era que sea completado en el horario de la clase para poder ayudarlos a dejar el entorno listo para trabajar.

Sentimos mucho por aquellos que tienen los tiempos mucho más ajustados. Podemos ver excepciones puntuales debidamente justificadas, pero hemos visto que dada la carga de trabajos prácticos, demasiado tiempo de entrega provoca su acumulación y la consiguiente sobrecarga de trabajo.

Podemos sentarnos a charlar el detalle de esta decisión en cualquier clase.

Invito a @inomdedeu @mmariguin-unrn a que ofrezcan su opinion al respecto

**Comment by Clirussa** [comment]
Buenas, el lunes quizás pueda acercarme para hablar con vos Martín por mí situación en particular, yo estoy en la comisión de Iván e Iván ya la conoce. Sobre el TP 0 en particular, en tiempo de hacer en la compu son unos minutos, pero lo que lleva tiempo es incorporar nuevo vocabulario e ideas nuevas, pensar que hay que hacer porque además se nos piden programas y formas de hacer puntuales que para quienes no lo hicimos nunca llevan tiempo de entender.

Saludos
Daysi

**Comment by inomdedeu** [comment]
Buen día,
comparto la opinion de Martín.  
Estamos centrados en que uds puedan trabajar y no atrasarce con las guias. 
El objetivo es llegar a fin de cuatrimestre, habiendo desarrollado y afianzado las buenas practicas de programación. Las cuales seran fundamentales para el resto de la carrera y en su desarrollo como profesional.

Teniendo en cuenta esto y que la practica 0 (como dice martin) es practicamente es un test de los programas estan funcionando. El tema de contar con una fecha de entrega acotada no es algo grave.

De todas formas, y como lo hablamos en clase, perder la posibilidad de promoción por haber entregado la P0 con 2 dias de demora no es algo que nadie desee (mucho menos nosotros). 
Por lo tanto, Daysi no te preocupes tanto por la entrega del P0, sino mas bien de ir generarando una rutina que te permita llevar al dia con las demas practicas. 

Saludos
Ivan
