### ISSUE TITLE
Sugerencia entrega de TPs

### ISSUE THREAD

**Issue by jingusci** [INGCOM-UNRN-P1/cursada-2023#80]
Sugerencia para los profesores:

Estaría bueno que el formultario de entrega de Trabajos practicos nos devuelva por mail alguna especie de "comprobante de entrega", capaz con los datos con los que llenamos el formulario.

Esto serviria para controlar la ansiedad luego de una entrega, las fechas limites pasan y al no tener la correccion uno empieza a dudar si entregó bien.

**Comment by martinvilu** [comment]
Ahora lo tiene, es un check al final, cerca del botón de enviar.
